### ISSUE TITLE
Reading Columns in a PDF

### ISSUE THREAD

**Issue by Kate-Lyndegaard** [Unstructured-IO/unstructured-inference#148]
Hi,

I am trying to read columns in a PDF, for example:
[08236061_3860_001_00_BK.pdf](https://github.com/Unstructured-IO/unstructured-inference/files/12028829/08236061_3860_001_00_BK.pdf)

Using:
```
    doc = process_file_with_model(filename=path, model_name=None)

    for element in doc.pages[0].elements:
        print(element.text)
```

The first column is read partially and then moves to the second column and reads that partially, and then reverts back to the first column. The entire page is read, however I would like to have each column extracted separately. Is there any way to do this?

**Comment by qued** [comment]
Hi @Kate-Lyndegaard ! We're working on logic to output elements in reading order for pages in columnar format. We implemented something a few releases ago, but found several instances where it got the order wrong in documents without columns, so we pulled it back until we had something better.

**Comment by Kate-Lyndegaard** [comment]
Hi @qued,
OK, that sounds great. I'll stay tuned:-)

**Comment by Kate-Lyndegaard** [comment]
Hi @qued,

I was able to extract the columns like this:

```import os
import pytesseract
from pdf2image import convert_from_path

filePath = r'C:\Users\KL\Weaviate\testdata\358454_planzeichnung.pdf'

doc = convert_from_path(filePath)  # works on PDFs with and without columns
path, fileName = os.path.split(filePath)
fileBaseName, fileExtension = os.path.splitext(fileName)

for page_number, page_data in enumerate(doc):
    txt = pytesseract.image_to_string(page_data, lang='deu')  # outputs German language text when German language training data is installed
    print("Page # {} - {}".format(str(page_number), txt))
```
