### ISSUE TITLE
chipperv2 unusable due to private model

### ISSUE THREAD

**Issue by 0-hero** [Unstructured-IO/unstructured-inference#254]
Since the chipperv2 integration is done with #232. Any expected release date for the model on the HF hub?

**Comment by cragwolfe** [comment]
Hi @0-hero , documents may be processed with chipperv2 soon via the API, https://api.unstructured.io/general/docs , bit the model itself will not be publicly available.

**Comment by 0-hero** [comment]
Thanks @cragwolfe It would amazing if it is open sourced though. It works very well on the hf space
