### ISSUE TITLE
Enabling offline huggingface model usage

### ISSUE THREAD

**Issue by cah-jake-bergren** [Unstructured-IO/unstructured-inference#325]
I'm working in an environment where calls to huggingface.co are blocked due to security concerns.

To init an OCR model for a call to `partition_pdf` in this environment, I can stage the model weights locally and set environment variables to properly utilize that model via init params and the `model_path` param. The problem is that when I include the `label_map` as required in that json, the keys of the label_map are converted to strings on-load when they need to be ints.

Can model init param JSON values be validated on-load via something like pydantic? That way this issue is avoided and custom init param values are not broken due to JSON serialization and deserialization.

Alternatively, you could allow me to pass the `model_path` param only.

**Comment by fwenyin** [comment]
hi i am also facing this issue, are there any workarounds for this? i have downloaded the model unstructuredio/yolo_x_layout locally, but it is not calling the local model
