### ISSUE TITLE
It seems that newer version depends on the older version of `onnx`

### ISSUE THREAD

**Issue by vykhovanets** [Unstructured-IO/unstructured-inference#336]
MacOS 14.4.1, M3
Python 3.12.3

> When I manually specify the version of `onnx`, which is available without compilation, I get the newest version of `unstructured-inference` where the `onnx` version wasn't hardcoded/specified. It happens to be version `0.5.19` from 1 September 2023. (I checked)

1. I tried to do the full installation with `pip install "unstructured[all-docs]"` into fresh venv, and got `onnx` build error.
2. I saw that there exists a newer version of `onnx` library and did `pip install "unstructured[all-docs]" onnx==1.16.0` successfully, at the first sight.
3. then I got an error with pytesseract.pytesseract.Error instead of unstructured_pytesseract.Error in `[layout.py](https://github.com/Unstructured-IO/unstructured-inference/blob/main/unstructured_inference/inference/layout.py)` at 276 line and noticed that pip installed the older versions of unstructured and unstructured-inference, and refuses to upgrade inference module without building `onnx==1.14.1` from scratch. 
<img width="308" alt="Screenshot 2024-04-16 at 23 44 46" src="https://github.com/Unstructured-IO/unstructured-inference/assets/21062175/29758750-af44-4ec1-85f8-cdca3d33d348">
<img width="357" alt="Screenshot 2024-04-16 at 23 46 18" src="https://github.com/Unstructured-IO/unstructured-inference/assets/21062175/72a91d84-d9a1-4609-919c-1d2e8b2839c8">
<img width="636" alt="Screenshot 2024-04-16 at 23 46 45" src="https://github.com/Unstructured-IO/unstructured-inference/assets/21062175/36ac2c66-76fe-4ec3-b823-335abe12d15e">
<img width="573" alt="Screenshot 2024-04-16 at 23 59 39" src="https://github.com/Unstructured-IO/unstructured-inference/assets/21062175/9eb866d1-cfa9-4d9f-a0a7-8370d7245d40">

**Comment by vykhovanets** [comment]
Probably, to resolve the issue with Mac installation, we need to increase the version of ONNX again, as done in #63.

**Comment by vykhovanets** [comment]
#2831 this issue connected

**Comment by scanny** [comment]
@vykhovanets Thanks for this, yes, I'm working on that today so it should be out by tomorrow :)

**Comment by scanny** [comment]
@vykhovanets v0.13.3 of `unstructured` was published last night, so this should work again now.

Closing as completed but let us know how you go :)
