### ISSUE TITLE
RuntimeError: Some images were not loaded.

### ISSUE THREAD

**Issue by udit-pandey-1** [Unstructured-IO/unstructured-inference#354]
OS: Ubuntu - 20.04.6 LTS
Python: 3.11
Requirements:
`
unstructured==0.14.2
unstructured-inference==0.7.33
pillow-heif==0.16.0
`

I am getting the following error when extracting text and images from pdf:
![image](https://github.com/Unstructured-IO/unstructured-inference/assets/160473849/07246bb7-54be-4c47-8f95-5ed5b2fc75a7)

The way I am using unstructured is:
![image](https://github.com/Unstructured-IO/unstructured-inference/assets/160473849/a943961e-0f59-4982-b1fd-e8e95822c5af)

Is there anyway we can fix this issue?

**Comment by tbs17** [comment]
Hi there, some of the troubleshooting steps we can consider:


**Check PDF File Accessibility:**

Ensure the PDF file is accessible and not corrupted.
Try opening the file with a PDF reader to verify its integrity.

**File Path and Permissions:**
Verify that the file path is correct.
Ensure you have the necessary permissions to read the file.

**Temporary File Issues:**

The error suggests a problem with accessing a temporary file. Ensure that the file is correctly created and accessible before processing it.
You might want to use a different temporary directory or explicitly manage the creation and deletion of temporary files.

**Handling Large Files:**

If the PDF is very large, it might cause issues during processing. Try with a smaller PDF to see if the problem persists.

**Library Versions and Dependencies:**

Ensure that all the libraries (unstructured, PyMuPDF, etc.) are up-to-date. There might be bug fixes or improvements in newer versions.


**Debugging and Logging:**

Add logging to your script to capture more details about where the error occurs.
Log the paths of the files being processed, and any other relevant information.

**Comment by udit-pandey-1** [comment]
Hi, thanks for the reply.
I got over the error by upgrading to `unstructured-inference==0.7.33`.
However, I am getting a different issue now and have opened an issue for it (https://github.com/Unstructured-IO/unstructured/issues/3102).

I'll anyways close this one for now.
