### ISSUE TITLE
ValueError when an empty table is detected

### ISSUE THREAD

**Issue by Baukebrenninkmeijer** [Unstructured-IO/unstructured-inference#357]
When running on a pdf, I got the following error: 
```
                               File
                             "/path_to_lib/lib/python3.11/site-packages/unstructured_inference/models/tables.py", line 667, in fill_cells
                                 table_rows_no = max({row for cell in cells for row in cell["row_nums"]})
                                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                             ValueError: max() arg is an empty sequence
```
My current understanding is this is out of the users control? Maybe we could have the option to ignore errors like this, and continue with the rest of the file. What seems like a good way forward? 

The file in question is this PDF: https://www.suez.co.uk/-/media/SUEZ-UK/Files/Publication/SUEZ-SustainabilityReport-2021-web.pdf, which is a big sustainability report. Hence missing one table is not great but not a deal breaker.

**Comment by christinestraub** [comment]
Hi @Baukebrenninkmeijer, Addressed on https://github.com/Unstructured-IO/unstructured-inference/pull/359. You'll need to upgrade `unstructured-inference` to 0.7.36.

**Comment by Baukebrenninkmeijer** [comment]
@christinestraub Awesome, thanks for the quick resolution!
