### ISSUE TITLE
ValueError in modela/tables.py

### ISSUE THREAD

**Issue by michaelstellanar** [Unstructured-IO/unstructured-inference#358]
In one of my input pdf files, the following is thrown:

  File "/home/michaelt/Work/sandbox_gradio/inference/lib/python3.12/site-packages/unstructured_inference/models/tables.py", line 667, in fill_cells
    table_rows_no = max({row for cell in cells for row in cell["row_nums"]})
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: max() iterable argument is empty

Debugging shows that cells array is, indeed, [].

Proposed fix:

    table_rows_no = max({row for cell in cells for row in cell["row_nums"]}, default=0)
    table_cols_no = max({col for cell in cells for col in cell["column_nums"]}, default=0)

It fixed my problem.

**Comment by christinestraub** [comment]
Closing this since it's assumed to be resolved, but feel free to reopen if you're still having this issue.
