### ISSUE TITLE
from_file broken, len(images) != len(layout)

### ISSUE THREAD

**Issue by hyperknot** [Unstructured-IO/unstructured-inference#51]
The from_file method in inference.layout.DocumentLayout.from_file is broken.

First, the load_pdf is duplicated 2x, which I guess it probably the hot-path.

Second, the loop breaks for me because len(images) != len(layout). I mean we are looping through layouts and then loading the image based on the layout's index? But for me the images != layouts. Actually len(images) = 0, is this because I have some dependency missing which is failing silently?

Are len(images) supposed to equal len(layout)? I'm running it on the official loremipsum.pdf as well. Platform is macOS.

```
layout = DocumentLayout.from_file("sample-docs/loremipsum.pdf")
```

https://github.com/Unstructured-IO/unstructured-inference/blob/6d2205b3e6fc6aa9b5bc7f4a1839fd66fd40413e/unstructured_inference/inference/layout.py#L74-L91

**Comment by hyperknot** [comment]
The solution was to `brew install poppler`. It's a pity that pdf2image and thus layoutparser silently fails if poppler is not installed. Probably a check has to be added in from_file which checks if the len()-s are not equal and raises an exception to please install Poppler.

The duplicated hot path is still a valid bug though.

**Comment by qued** [comment]
Thanks for finding this. I'm doing a [quick update](https://github.com/Unstructured-IO/unstructured-inference/pull/52) to remove the duplicate line, then I'll try to reproduce the mismatched `len` behavior.
