### ISSUE TITLE
Incompatibility with Python 3.11: RuntimeError when trying to install onnxruntime (1.14.1)

### ISSUE THREAD

**Issue by ibiscp** [Unstructured-IO/unstructured-inference#83]
When attempting to use the library with Python 3.11, I encountered a RuntimeError while trying to install onnxruntime (1.14.1), it fails to find any installation candidates for the package. This seems to be an incompatibility issue with Python 3.11, and it would be great if the library could be updated to support the latest Python version.

There is already an issue opened [here](https://github.com/microsoft/onnxruntime/issues/13482), but it seems that the library has not been updated to address this issue yet.

**Comment by benjats07** [comment]
Hi!

I made some research and seems like a new release of onnxruntime is expected in 3-4 months, so maybe will be supported then, I'll keep an eye on it.

https://github.com/microsoft/onnxruntime/issues/14880

**Comment by qued** [comment]
As far as I can tell this issue has been resolved. For months `unstructured` has been running with `unstructured-inference` on Python 3.11 and using a default model that uses `onnxruntime`.
