### ISSUE TITLE
Error: cannot import name 'etree' from 'lxml'

### ISSUE THREAD

**Issue by codingbutstillalive** [Unstructured-IO/unstructured-inference#90]
When trying to execute

`from unstructured.partition.auto import partition

elements = partition("example-docs/layout-parser-paper.pdf")`

I get the above mentioned error. However, `import lxml` works just fine. For some strange reason, the "etree" submodule cannot be imported.

The exaxt error message was: "ImportError: cannot import name 'etree' from 'lxml' (/usr/lib/python3/dist-packages/lxml/__init__.py)".

**Comment by MthwRobinson** [comment]
Hi @codingbutstillalive - thanks for reporting this. What `lxml` and Python version are you using? 

Found [this issue](https://github.com/WeblateOrg/weblate/issues/4183) that may be helpful. They suggest the following:

```
pip uninstall lxml
pip install --no-binary lxml
```

**Comment by MthwRobinson** [comment]
Do you know what Python version and operating system is running on Paperspace vs. Colab?

**Comment by qued** [comment]
Searching around for other occurrences of this error has led me to suspect the compiled binary extension that contains `etree` doesn't match something about the Python version that's trying to import it.

- [Here](https://stackoverflow.com/questions/53406638/importerror-cannot-import-name-etree-on-python-3-6) some people were able to solve it by reinstalling or finding and installing the correct pre-compiled binaries for their system and Python version.
- [Here](https://stackoverflow.com/questions/66402511/cannot-import-etree-from-lxml) and [here](https://stackoverflow.com/questions/58892522/cannot-import-name-etree-in-python-3-7-how-can-i-get-this-working) it's suggested that there is more than one installation of Python and `lxml` and the user should try getting rid of one of them, although these are on Windows.
- [Here](https://stackoverflow.com/questions/13749916/receiving-importerror-cannot-import-name-etree-when-using-lxml-in-python-on-m) same type of suggestions, possibly multiple installations of `lxml`.

From your traceback it looks like it's looking in your system Python packages for `lxml`. Maybe that's a clue? Did you install it into a virtual or conda environment and it's importing from the wrong place?

In any case I would check for multiple installations of `lxml` and conflicting Python environments (maybe check the `PYTHONPATH` environment variable to see where it's looking for packages and in what order). If you find other installations of `lxml`, remove them and try installing again into the desired environment.

**Comment by codingbutstillalive** [comment]
I did some research and I found this - though I was using another container image, I suppose the way how paperspace maintains stuff in them might still be the same:

"Whereas paperspace installs packages using conda. The question is will this mess up things? The answer to this question is no. The place where you need to use conda/mamba is the stuff that uses the GPU. Especially, for PyTorch or TensorFlow. Conda/mamba has a way of installing the CUDA toolkit requirements so that we don’t need to worry about installing the CUDA SDK separately. Conda maintains the CUDA versions as they need to mesh properly with the PyTorch version."

Could this maybe explain it?

**Comment by qued** [comment]
It's a clue there might be a conda environment. So it's possible the `lxml` installation you want is in a conda environment, and it's trying to import from the system Python environment.

**Comment by codingbutstillalive** [comment]
Yes. That seems to be the case.

How would I then install detectron2? The manual only describes installation with pip. I am not quite sure :)

**Comment by qued** [comment]
In theory conda should be able to handle and keep track of packages installed into a conda environment with pip (although in practice this hasn't always been the case when I've used conda) so you should just be able to follow the instructions from the documentation after activating your conda environment. As a last resort, you could install the [detectron2 conda package](https://anaconda.org/conda-forge/detectron2) on `conda-forge`. Note this isn't the version we recommend (0.6 was released in November 2021 and there hasn't been a release since) and I don't have any experience with this packaging but if nothing else works it's something to try.

You didn't specifically say that this was a problem, but I'll just mention that detectron2 needs to be installed _after_ torch is installed, which is why we don't put it in the requirements to be installed concurrently with torch.

**Comment by codingbutstillalive** [comment]
I could in fact solve the issue. But then I encountered a new one.

The lxml issue seemed to have been related to the version.

The version installed as a dependency of detectrom was 4.5 instead of 4.9.
When I removed and re-installed, it got solved.

So installation succeeded. But when running the code, there was a message
that "detectron was probably not correctly installed".

I assume this could be the case because the Torch version pre-installed on
Paperspace might not be compiled with the same CUDA version like detectron
and pip cannot detect and act on this. I read something along these lines
on the poetry github page concerning detectron.

Maybe I need to use another than the default git repository URL? I saw you
provide different pre-compiled wheels for it, right?

How can I determine which would match to each other?

qued ***@***.***> schrieb am Sa. 29. Apr. 2023 um 19:31:

**Comment by codingbutstillalive** [comment]
> In theory conda should be able to handle and keep track of packages installed into a conda environment with pip (although in practice this hasn't always been the case when I've used conda) so you should just be able to follow the instructions from the documentation after activating your conda environment. As a last resort, you could install the [detectron2 conda package](https://anaconda.org/conda-forge/detectron2) on `conda-forge`. Note this isn't the version we recommend (0.6 was released in November 2021 and there hasn't been a release since) and I don't have any experience with this packaging but if nothing else works it's something to try.
> 
> 
> 
> You didn't specifically say that this was a problem, but I'll just mention that detectron2 needs to be installed _after_ torch is installed, which is why we don't put it in the requirements to be installed concurrently with torch.

I could in fact solve the issue. But then I encountered a new one. The lxml issue seemed to have been related to the version. The version installed (as a dependency of detectron?) was 4.5 instead of 4.9. When I removed and re-installed lxml, it got resolved. So installation succeeded. But when running the code, there is now an error message that "detectron was not correctly installed". I assume this could be the case because the Torch version pre-installed on Paperspace might not be compiled with the same CUDA version like the one detectron2 used and pip cannot detect and act on this. I read something along these lines on the poetry github page concerning detectron2. Maybe I need to use another than the default git repository URL? I saw you provide different pre-compiled wheels for it, right? How can I determine which would match each other?

**Comment by qued** [comment]
> I assume this could be the case because the Torch version pre-installed on Paperspace might not be compiled with the same CUDA version like the one detectron2 used and pip cannot detect and act on this.

That sounds pretty close to me, although I'm not sure if CUDA is involved. As far as I know detectron needs to be matched with the torch version (which is why torch needs to be pre-installed when installing detectron). I don't know if switching to a different detectron version will work, my impression is that detectron is capable of using whatever version is installed (within reason) when installing, but then you have to stick with that version when using detectron. So my guess would be detectron is mixed up about which installed torch version it should be "matched" with.

What I would want to do in your situation is set up a clean virtual environment with no interference from other installed components, but I don't know how much trouble that is to set up on your Paperspace machine.

**Comment by codingbutstillalive** [comment]
I did this using venv. And the installation still didn’t fully work. It is
really some nasty thing.

thanks for your help nevertheless. I will actually give it up by now.

qued ***@***.***> schrieb am Do. 4. Mai 2023 um 20:28:

**Comment by qued** [comment]
@codingbutstillalive Incidentally, we no longer require installation of detectron2, as long as you can install the ONNX runtime you should be able to use the detectron2 model. Closing issue in light of the update.
