### ISSUE TITLE
What is the difference between "unstructured-inference" and "unstructured[local-inference]"?

### ISSUE THREAD

**Issue by codingbutstillalive** [Unstructured-IO/unstructured-inference#91]
And can you compile and execute "Detectron2" also on an Intel Macbook Pro (2018) without an Nvidia Graphics card?

**Comment by qued** [comment]
Hi @codingbutstillalive !

1. `unstructured-inference` is this repository as well as the name of the associated pypi package while `unstructured[local-inference]` is the pypi package for the `unstructured` repository, with a flag for the option to install the `unstructured-inference` package as well for PDF/image processing.
2. Yes, you can install and run `detectron2` on a 2018 intel Macbook pro without a graphics card.

**Comment by codingbutstillalive** [comment]
I would be happy to receive some info on my last question, i.e. what are the benefits of detectron2 instead of DocParser, LayoutLMv3, or Donut. 

Moreover. What is then the difference between "unstructured" and "unstructured-inference"?

**Comment by qued** [comment]
DocParser I'm not familiar with. LayoutLMv3 has a conflicting license, so we can't use it. Donut we can use and have a built in model with similar architecture. I should note that you can use an external model by writing a light wrapper around it.
